Add Rust binary files for multiple architectures and versions
mandiant/flare-floss-testfiles pull request #14
Opened 2023-08-01 14:07 UTC by Arker123

This PR adds binary files for the Rust programming language, compiled for various architectures and versions, to the repository. The binary files include support for architectures such as 386 and amd64, and versions 1.59.0, 1.65.0 and 1.69.0.

2023-08-05 08:59 UTC, Arker123 commented on language/rust/rust-unknown-binaries/Readme.md
> +This repository contains binary files for Rust programming language compiled for various architectures and versions. Please note that the source code for these binaries is not available and their ori
As an initial step in identifying Rust code, you had supplied me with these files.😄

2023-08-06 05:58 UTC, Arker123 commented
I've noticed that our rust identification module has mistakenly flagged 386_rust1.65.0 as rust binary, while on further analysis, I found out that it is not. We should take a closer look at this.

2023-08-07 13:02 UTC, mr-tz commented on language/rust/rust-unknown-binaries/Readme.md
> +- amd64_rust1.69.0: Rust binary compiled for Windows 64-bit (amd64) architecture, version 1.69.0.
Good question, @Arker123 any insights on this?

2023-08-10 09:13 UTC, Arker123 commented on language/rust/rust-unknown-binaries/Readme.md
> +- amd64_rust1.69.0: Rust binary compiled for Windows 64-bit (amd64) architecture, version 1.69.0.
These 1.69.0 versions are wild binaries, so their sources could vary greatly. This might explain the larger sizes. 😄

2023-08-10 09:14 UTC, Arker123 commented
Current extraction percentages:- 

File:  1.64.0_amd64
Percentage of string extracted:  102.41
----

File:  1.59.0_amd64
Percentage of string extracted:  83.42
----

File:  1.59.0_i386
Percentage of string extracted:  99.02
----

File:  1.65.0_amd64
Percentage of string extracted:  100.73
----

File:  1.47.0_amd64
Percentage of string extracted:  96.04
----

File:  1.68.1_amd64
Percentage of string extracted:  100.89
----

File:  1.69.0_i386
Percentage of string extracted:  100.45
----

2023-08-10 09:27 UTC, williballenthin commented on language/rust/rust-unknown-binaries/Readme.md
> +- amd64_rust1.69.0: Rust binary compiled for Windows 64-bit (amd64) architecture, version 1.69.0.
ah, ok. the naming suggests that they're maybe from all the same source, so i was confused. perhaps we can name these files after their sha256 and place them into a directory structure that describes their compiler version and arch?

like `language/rust/1.69.0/i386/asdfafdsafsdafdsa.exe_`

2023-08-10 09:28 UTC, williballenthin commented on language/rust/rust-unknown-binaries/Readme.md
> +This repository contains binary files for Rust programming language compiled for various architectures and versions. Please note that the source code for these binaries is not available and their ori
please update the documentation to explain that the files came from VT.

2023-08-10 09:29 UTC, williballenthin commented
what does it mean for there to be more than 100% of strings extracted? lets prioritize fixing the script and/or its interpretation before we use it further.

2023-08-10 10:00 UTC, Arker123 commented
Absolutely, let's fix the coverage script first.😄

2023-08-14 08:05 UTC, mr-tz requested changes

2023-08-14 08:05 UTC, mr-tz commented on language/rust/rust-unknown-binaries/bin/1.59.0/1.59.0_i386
this name needs to be updated like the others

2023-08-14 08:05 UTC, mr-tz commented on language/rust/rust-unknown-binaries/Readme.md
> +- amd64_rust1.69.0: Rust binary compiled for Windows 64-bit (amd64) architecture, version 1.69.0.
let's rather describe the dir/file structure, as it's pretty clear now

2023-08-14 09:41 UTC, mr-tz commented on language/rust/rust-unknown-binaries/Readme.md
> +</table>
I think the above is clear, nice job on that.

2023-08-14 10:53 UTC, merged

2023-08-14 10:53 UTC, mr-tz commented
thanks!